services:
  - type: web
    name: okr-tracker
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn.conf.py
    envVars:
      - key: SPREADSHEET_ID
        sync: false
      - key: GCP_PROJECT_ID
        sync: false
      - key: GCP_PRIVATE_KEY_ID
        sync: false
      - key: GCP_PRIVATE_KEY
        sync: false
      - key: GCP_CLIENT_EMAIL
        sync: false
      - key: GCP_CLIENT_ID
        sync: false
      - key: GCP_CLIENT_CERT_URL
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: SENDER_EMAIL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.6
